SELECT p.PRODUCT_ID, 
       p.PRODUCT_NAME, 
       SUM(o.AMOUNT * p.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER o
JOIN FOOD_PRODUCT p ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE EXTRACT(YEAR FROM o.PRODUCE_DATE) = 2022
  AND EXTRACT(MONTH FROM o.PRODUCE_DATE) = 5
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID ASC;
