WITH ReviewCount AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    limit 1
)
SELECT p.MEMBER_NAME,
       r.REVIEW_TEXT,
       date_format(r.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM REST_REVIEW r
JOIN MEMBER_PROFILE p ON r.MEMBER_ID = p.MEMBER_ID
WHERE r.MEMBER_ID IN (SELECT MEMBER_ID FROM ReviewCount)
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC;
