WITH GRADE_SUM AS (
    SELECT 
        EMP_NO,
        SUM(SCORE) AS TOTAL_SCORE
    FROM 
        HR_GRADE
    WHERE 
        YEAR = 2022
    GROUP BY 
        EMP_NO
)
SELECT 
    G.TOTAL_SCORE AS SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM 
    GRADE_SUM G
JOIN 
    HR_EMPLOYEES E ON G.EMP_NO = E.EMP_NO
WHERE 
    G.TOTAL_SCORE = (SELECT MAX(TOTAL_SCORE) FROM GRADE_SUM);
