SELECT 
  b.TITLE AS TITLE, 
  b.BOARD_ID AS BOARD_ID, 
  r.REPLY_ID AS REPLY_ID, 
  r.WRITER_ID AS WRITER_ID, 
  r.CONTENTS AS CONTENTS, 
  DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY r
LEFT JOIN USED_GOODS_BOARD b
  ON b.BOARD_ID = r.BOARD_ID
WHERE DATE_FORMAT(b.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY r.CREATED_DATE ASC, b.TITLE ASC;
